name: Build (iOS | SIM | Mac) Arm64 Framework

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          brew install --formula cmake ninja
          python3 -m pip install --upgrade pip
          pip3 install conan==2.2.3

      - name: Download ios.toolchain.cmake
        run: |
          curl -L https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake \
            -o ios.toolchain.cmake

      - name: Run build script
        run: |
          chmod +x scripts/build-ios-sim-mac-xcframework.sh
          scripts/build-ios-sim-mac-xcframework.sh

      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kuzu.xcframework
          path: build/Kuzu.xcframework
